README.md
phone/package.json
phone/src/config/default.json
phone/src/index.tsx
phone/yarn.lock

As the title says. There is an option added to `config/default.json` to disable it for users worried about privacy concerns.

Feat: Added Sentry integration for exception metrics

---

resources/client/cl_utils.ts
resources/client/client.ts
resources/utils/fivem.ts

This new Feature allows for us to wrap net events in a promise. Here are some examples.
```ts
try {
const result = await ClUtils.emitNetPromise(
'npwd:promiseEvent',
'arg1',
'arg2'
);
console.log('Resolved:', result);
// If the promise is rejected, we catch it here
} catch (e) {
console.error('Promise Rejected:', e);
}
```
This is how we listen to these promised events on the server. The first param to the callback will always be the name of the event that we must emit back to the client. The rest of the params, are whatever was passed to `emitNetPromise`. When responding, we must use the passed eventName, the source, and either the result or an error. The following example is a successful server transaction, where the data returned is 'Amazing data returned'.
```ts …
```

feat(client/net): Promisfied net events

---

resources/server/sv_call.ts

Call history Is now ordered by ID so recent calls show up first instead of last. Previously it was just at the bottom.
(Courtesy of Chip)

Fix: Call history is now sorted.

---

fxmanifest.lua

"watch" in the phone package.json allows rebuilds on any code changes. This doesn't seem functional as of [this commit](https://discord.com/channels/791854454760013827/791854455468458042/816454853621710868) which excludes `dev.js` from the `fxmanifest.lua`.
This change just wildcards JS files so both `yarn build` and `yarn watch` are functional.

[Bug] Yarn watch isn't working

---

phone/src/apps/bank/hooks/useBankService.ts
phone/src/apps/calculator/components/Calculator.tsx
phone/src/apps/contacts/hooks/useContactsService.ts
phone/src/apps/messages/hooks/useMessageService.ts
phone/src/apps/notes/hooks/useNotesService.ts
phone/src/apps/sellout/hooks/useSelloutService.ts
phone/src/apps/twitter/hooks/useTwitterService.ts
phone/src/locale/en.json
phone/src/ui/components/Snackbar.tsx
phone/src/ui/hooks/useSnackbar.ts

Change to Snackbar message property to allow for any string rather than a translation key
**New**
```jsx
export const Snackbar = () => {
const classes = useStyles();
const { alert } = useSnackbar();
return (
<div className={classes.root}>
{alert ? <Alert severity={alert.type}>{alert.message}</Alert> : null}
</div>
);
};
```

tweak(phone/snackbar-provider): Altered API

---

phone/src/Phone.tsx
phone/src/ui/components/Alert.tsx
phone/src/ui/components/PhoneSnackbar.tsx
phone/src/ui/hooks/useSnackbar.ts
phone/src/ui/providers/SnackbarProvider.tsx

This fixes the animations issues when transitioning in and out from an Alert. This also simplifies the useEffect logic and there isn't much of a need for a timeout + useEffect
[fix(phone/snackbar): Fixed animations & simplified logic](https://app.gitkraken.com/glo/card/9ae022fca0634990ab6e1d946146d81d)

fix(phone/snackbar): Fixed animations & simplified logic

---

phone/src/apps/dialer/components/DialerApp.tsx
phone/src/apps/dialer/components/DialerInput.tsx
phone/src/apps/dialer/components/views/DialPage.tsx
phone/src/apps/dialer/components/views/DialerHistory.tsx
phone/src/apps/dialer/context/InputContext.tsx
phone/src/apps/dialer/hooks/useDialHistory.ts
phone/src/apps/dialer/hooks/useDialService.ts
phone/src/index.tsx
phone/src/locale/en.json
resources/client/cl_call.ts

Time has been changed to a relative format. Locale specifics are pending
merge of #168.
Several typos have been fixed where "DAILER" was referenced instead of
"DIALER"
A translation key was added for when a user has no call history.
The input box has been unlocked so users can use their keyboard directly
rather than using the dial pad.

tweak(dialer): Several fixes and improvements

---

phone/package.json
phone/src/Phone.tsx
phone/src/apps/settings/components/SettingsApp.tsx
phone/src/apps/settings/hooks/useSettings.ts
phone/src/locale/en.json
phone/yarn.lock

You can now reset your settings to default using the action in the Settings App
Setting schema validation has been added that will temporarily reset to default settings if
the JSON string contains unexpected values. A alert will pop up informing the user
that they should reset to default settings using the action in the settings app,
as a permanent solution.

feat(phone/settings): Schema validation & Reset Settings Action

---

import.sql

Made the default identifier length `48` since this is the maximum length if `license:` isn't removed and is something those using `esx_kashacters` will already have to do. I also adjusted the instances where it was `255` for some reason so those are `48` as well.
The addition of back ticks is just for formatting. The readability is much better inside VS and sql editors as the text is highlighted as a result. Its's also how most of the SQL was anyways.

RFR: Adjust identifier length + add backticks.

---

resources/client/cl_call.ts

mumble-voip is no longer maintained and is recommended to not be used as it is broken & doesn't have modern features.

feat(client/call): make pma-voice the default export

---

phone/src/Phone.tsx
phone/src/os/phone/hooks/state.ts
phone/src/os/phone/hooks/usePhone.ts
phone/src/os/phone/hooks/usePhoneService.ts
resources/client/cl_main.ts
resources/server/players/player.controller.ts
resources/server/players/player.service.ts

Fix: Player ready stuff

---

phone/src/apps/bank/components/transfers/TransferModal.tsx
phone/src/apps/contacts/components/views/ContactInfo.tsx
phone/src/apps/dialer/components/DialerInput.tsx
phone/src/apps/marketplace/components/form/ListingForm.tsx
phone/src/apps/messages/components/form/MessageInput.tsx
phone/src/apps/messages/components/form/NewMessageGroupForm.tsx
phone/src/apps/notes/modal/NoteModal.tsx
phone/src/apps/settings/components/WallpaperModal.tsx
phone/src/apps/twitter/components/TwitterSearch.tsx
phone/src/apps/twitter/components/images/ImagePrompt.tsx
phone/src/apps/twitter/components/tweet/TweetMessage.tsx
phone/src/ui/components/Input.tsx
phone/src/ui/components/ProfileField.tsx
phone/src/ui/components/SearchField.tsx
resources/client/cl_main.ts
typings/phone.ts

Disable walking when an inputfield is focused

---

README.md
import.sql
phone/src/apps/camera/components/CameraApp.tsx
phone/src/apps/marketplace/hooks/state.ts
phone/src/os/debug/InjectDebugData.ts

Iodine (iodine.gg) has rebranded to Fileglass (file.glass). Whilst the current Iodine links still work, they add extra, unnecessary overhead having to redirect from Iodine.

Rebrand Iodine links to Fileglass

---

config.json
resources/server/utils/getPlayerGameLicense.ts
typings/config.ts

Hi,
This PR is now done from the develop branch as requested by itschip.
**Reposting old info :**
My server is currently using discord identifier to register users, and many other servers will be using steam ids.
So i'm suggesting make "license:" configurable for anyone would be a good idea.
Changing it from "license" to "discord" will not lead to any other issue from my testing as all identifier are string type even if they only contains number.

feat(config): Add the ability to change used identifier type

---

fxmanifest.lua

screenshot-basic is required for camera functionality so its a dependency and should be listed as such imo. I don't really see it being an optional thing since photos are going to be integrated into messages and at some point I think marketplace if I'm not mistaken.

fix: Add dependency into manifest

---

resources/client/cl_main.ts
resources/client/cl_utils.ts
resources/server/misc/functions.ts
resources/server/players/player.controller.ts
resources/server/players/player.interfaces.ts
resources/server/players/player.service.ts
typings/phone.ts

An event is triggered on the client after the player is added or removed, updating the `playerLoaded` value.
Default state of playerLoaded is false and, if not using multichar, will be changed by the playerSpawned event; not sure if it's necessary (not sure if #330 applies to regular spawning).
I'm not sure how `generateUniquePhoneNumber()` worked at all, but apparently it does for non-multichar? Didn't await result and just ended up querying with a promise as the first parameter; regardless, I needed to use rawExec to successfully query the database or I would get some error related to an undefined value and reading 'pool'. 😕
Refactor and improve this however since it could 100% be done cleaner and I'm not sure where you would want the playerReady function defined.

fix: Multicharacter loading and number generation

---

resources/server/messages/messages.utils.ts

Resolves this error only I get 
A console log of `console.log(phoneNumber, userIdentifier, identifier)` would print the `identifier` as undefined.
Taso refactored some to improve readability.

fix(messages): participant identifier being null

---

resources/client/cl_photo.ts
typings/photo.ts

feat(phone/photo): emit an event when exiting/entering photo mode

---

phone/src/apps/messages/hooks/useMessageNotifications.ts
phone/src/locale/en.json
resources/server/messages/messages.service.ts

Create a message conversation for the receiving client when a message broadcast is emitted.
The introduced feature is not final, nor should it be. 
Messages needs to refactor into having API and "local" nui functionality (not doing that now)

Gh 348/repopulate conversations

---

config.json
resources/server/bridge/sv_exports.ts
resources/server/players/player.controller.ts
typings/config.ts

Rename 'enableMultiChar' to 'useResourceIntegration'. Better name convention, and *hopefully* less confusion

tweak(config): improve name convention for resource integration config

---

resources/package.json
resources/server/db/db_utils.test.ts
resources/server/db/db_utils.ts
resources/server/db/pool.ts

Utilises the built-in parser from mysql-2 when string contains `mysql://`, otherwise uses the (improved) semicolon parser.
This brings the parser in-line with oxmysql which has more compatibility with mysql-async strings than the current one.

refactor(db): change mysql_connection_string parsing

---

resources/client/cl_controls.lua

If your phone is open and another player is close to you, pressing R will trigger a light melee attack.
Disabling control 140 will fix it

Disable light melee attack

---

config.json
phone/src/apps/camera/components/grid/GalleryGrid.tsx
phone/src/apps/contacts/hooks/useContactsAPI.ts
phone/src/apps/marketplace/components/form/ListingForm.tsx
phone/src/apps/match/components/profile/ProfileForm.tsx
phone/src/apps/twitter/components/profile/Profile.tsx
phone/src/locale/en.json
resources/client/cl_photo.ts
resources/server/contacts/contacts.service.ts
resources/server/marketplace/marketplace.controller.ts
resources/server/marketplace/marketplace.service.ts
resources/server/match/match.service.ts
resources/server/messages/messages.service.ts
resources/server/messages/messages.service.ts.rej
resources/server/notes/notes.service.ts
resources/server/photo/photo.service.ts
resources/server/twitter/twitter.service.ts
resources/server/utils/imageFiltering.ts
typings/config.ts
typings/contact.ts
typings/marketplace.ts
typings/match.ts
typings/photo.ts

This is a basic PR to get general ideas to improve "image safety".
The main current issue is that users are allowed to post images from any website, this isn't something that's unique to npwd and is something a lot of larger tech companies have something in place for. See `https://images-ext-2.discordapp.net/external/kPbHbSF3VICIZj3y5aDagCzU891BqQcHBtMzz3ygEkE/https/i.dillonskaggs.dev/RpptWjd0?width=245&height=300`
Why is this an issue?
The most obvious thing is that bad actors can IP dump the entire server if they have their own image server setup.
Current Missing Features:

feat: basic image filtering

---

LICENSE

This is approved OSI license unlike the NC-BY-SA license in use previously
In order to receive funding from Cloud service providers such as AWS, NPWD needs to use an OSI approved license as listed [here](https://opensource.org/licenses). To best reflect our values, we feel that the GPLv3 license is most appropriate. This change is incredibly important for consumers, and should be noted.

chore(license): move towards the GPLv3 OSS license 

---

.github/actions/bump-manifest-version.js
.github/workflows/tagged-releases.yml
fxmanifest.lua

Based on #619 with minor tweaks and fixes.
The job will run once the create-tagged-release job is finished to avoid situations where the job failed but the manifest was updated anyways.
The ci was tested on my fork with the sentry step removed.
Resolves #616.

ci(tagged-releases): Automatic fxmanifest version bump

---

phone/src/os/notifications/components/NotificationBar.tsx

Do not apply any text transformations to the cell provider in the notification bar. Closes #774

fix(phone/notibar): don't apply text transform to cell provider

---

phone/package.json
phone/src/apps/twitter/components/tweet/Tweet.tsx
phone/yarn.lock

The XSS package is significantly smaller compared to DOMPurify, while still adequately mitigating against the possible XSS vector when processing Tweet content.
Sizes (Unpacked):
DOMPurify - 676 kB
XSS - 146 kB

perf(phone/twitter): utilize xss package in lieu of DOMPurify

---

config.default.json
resources/server/utils/imageFiltering.ts

Change image filtering to fix users being able to put this in a url:
`https://attacker.com/imgur.com`
With the old code this would be considered a safe url because it contains imgur.com, now it actually checks the hostname with a new URL object.

fix: change image filtering

---

phone/src/apps/contacts/components/ContactsApp.tsx
phone/src/apps/dialer/components/DialerInput.tsx
phone/src/apps/messages/components/MessagesApp.tsx
phone/src/apps/messages/components/form/NewMessageGroupButton.tsx
phone/src/apps/twitter/components/buttons/TweetButton.tsx
phone/src/os/keyboard/hooks/useKeyboardService.ts
phone/src/ui/components/Input.tsx

This PR aims to fix the weapon firing bug when a user clicks to focus an element.  The onFocus attribute used for the input fields was changed to onMouseUp to prevent firing the toggleKeys function simultaneously when the user pressed their mouse click (since firing the function at the same time the click is pressed will cause the bug to re-occur given the way that SetNuiFocusKeepInput functions).

fix(phone/keyboard): Swap onFocus attributes to onMouseUp to fix weapon firing

---

phone/src/apps/contacts/components/ContactsApp.tsx
phone/src/apps/dialer/components/DialerInput.tsx
phone/src/apps/messages/components/MessagesApp.tsx
phone/src/apps/messages/components/form/NewMessageGroupButton.tsx
phone/src/apps/twitter/components/buttons/ReplyButton.tsx
phone/src/apps/twitter/components/buttons/TweetButton.tsx
phone/src/os/keyboard/hooks/useKeyboardService.ts
phone/src/ui/components/Input.tsx

In addition to the previous PR #849 function handleNUIKeyboardPress() was added to handle on key-down press for Tab to prevent the user from switching to the next selectable field which would fire the onBlur effect and cause player movement to be re-enabled whilst also being able to type in the next field.

fix(keyboard/mouse): Disable tab button press on keydown

---

apps/phone/package.json
apps/phone/src/apps/contacts/components/views/ContactInfo.tsx
apps/phone/src/apps/twitter/components/tweet/TweetList.tsx
config.default.json
packages/database/src/twitter/index.ts
pnpm-lock.yaml
typings/config.ts

- Added infinite scrolling for twitter tweets with virtualization of DOM elements
- Added new config option to change the limit of results per request for tweets.
- Hide pay contact button when config is disabled
* [✓] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [✓] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [✓] Have you built and tested NPWD in-game after the relevant change?
Concept of infinite scrolling while limiting the DOM elements to just what is in the view.. it will only render new DOM elements when the user scrolls up and down while culling elements out of view to keep the performance …

Added virtualize infinite scrolling for twitter feed & hidden contact pay button

---

apps/phone/src/apps/darkchat/components/modals/UploadMedia.tsx
apps/phone/src/apps/darkchat/components/ui/ChannelItem.tsx
apps/phone/src/apps/darkchat/components/ui/NewChannelModal.tsx
apps/phone/src/apps/darkchat/components/views/ChatListView.tsx
apps/phone/src/ui/components/Modal.tsx

There were a few styling issues in the darkchat app that made buttons/components hard to see / nearly invisible. This PR aims to fix those styling issues so that all buttons and components can be easily seen in both light and dark theme. 
Note: We found that these styling issues are caused by the Tailwind styles imported in the `phone/src/main.css`. It is styling `button` tag directly and as a result overrides the MUI styles in many places. This solution is more of a short term / bandaid fix until a longer term solution is figured out with the use of Tailwind and MUI styles.
**Issue 1:  List item font color was too dark in dark theme**
**Issue 2: Add channel in bottom right corner was not visible in dark theme**
BEFORE: 
AFTER: 
**Issue 3: Modal X button …

Fix styling issues for darkchat app

---

apps/phone/src/apps/contacts/components/List/SearchContacts.tsx
apps/phone/src/apps/contacts/components/views/ContactInfo.tsx

On the Contacts App, ContactInfo component, the three `<Input />` fields were not disabling keys. 
If a player used WASD it would allow them to walk even while the input had focus, and other keys that were bound would also trigger.
Switched the component to use the `<InputBase />` component which is properly handling the keypresses. As a result of changing to this Input box, the component had to have the styles re-applied, so some style override changes were added.
BEFORE
AFTER
The Search box had the same issue so I used the `<SearchField />` component that other apps (like Messaging) are using.
BEFORE
AFTER
Recording showing that it no longer tries to make you move:
https://clipchamp.com/watch/JnjnPZK90pY

Fix: Contacts App Input boxes were not disabling key actions

---

config.default.json

Added `media.discordapp.net` to the `safeImageUrls`.
When you copy image URL from the camera app for example, the URLs are stored using the media.discordapp.net URL path.
Ex: https://media.discordapp.net/attachments/951758064728559636/1125303590987251742/fivemscreenshot.webp

Add alternate discord url to the imageSafety config

---

apps/phone/src/apps/camera/components/modal/ShareModal.tsx
apps/phone/src/apps/camera/components/modal/modal.styles.ts

This PR fixes some of the styling issues in the camera app.
_Note: We found that these styling issues are caused by the Tailwind styles imported in the phone/src/main.css. It is styling button tag directly and as a result overrides the MUI styles in many places. This solution is more of a short term / bandaid fix until a longer term solution is figured out with the use of Tailwind and MUI styles._
BEFORE
AFTER

Camera: Fix camera styles

---

apps/game/client/cl_twitter.ts
apps/game/server/twitter/twitter.service.ts
apps/phone/src/apps/twitter/hooks/useTwitterActions.ts
apps/phone/src/apps/twitter/hooks/useTwitterService.ts
typings/twitter.ts

Problem:
When a tweet is liked or a like is removed from a tweet, other users do not see the tweet count changing. A user only sees the count change locally from their own like/remove like. 
This PR solves this problem by broadcasting the add/remove like to all players so that the counts are accurately reflected on all clients and are kept up to date.
- updated `localToggleLike` to only handle toggling the `isLiked` field
- added `updateTweetLikes` that is received on all clients to update the `likes` count by incrementing or decrementing depending on if the like was added/removed
Additionally this PR adds a notification when a user's tweet is liked. Notifications will only show if the user is not currently looking at the twitter app. 
Demo: …

Twitter: Broadcast twitter add / remove like and notify user when their tweet is liked

---

apps/phone/src/os/phone/hooks/usePhoneVisibility.ts

If you run the app from `apps/phone` and use `yarn dev` you can develop the app in the browser. 
Currently the phone will never appear on the screen. This is because the `usePhoneVisibility()` hook positions the phone off screen so that when you are in game the phone only shows when its opened. When in the dev/browser mode we want the phone to always show. Added a check for `isEnvBrowser` to know if we are in game vs the browser, and if in browser we do not position the phone off screen. 
Ex: Phone displays correctly in browser

Fix: Add isEnvBrowser check for running app in dev mode

---

apps/game/server/photo/photo.service.ts

Problem: If the user has the config `useWebhook: true`, picture files are created in the `uploads/` folder but are never cleaned up / deleted after the upload succeeds, thus the files continue to build up on the machine. 
Repro: 
- set useWebhook: true and set discord webhook to upload to
- take a picture in game with camera app
- look at the `uploads/` folder and you will see that the file created for the photo still exists
- expected: after successful upload the file should be deleted
There is already a file cleanup called below for the codepath when useWebhook is false. The fix was to add the same file path cleanup inside the useWebhook flow.

Delete photo file after upload succeeds

---

apps/phone/src/apps/messages/hooks/useMessageService.ts

**Problem:** If a user receives a text message, but has never opened the message conversation before, they will not receive a notification on their phone.
Fixes issue: https://github.com/project-error/npwd/issues/1017
**Repro steps:**
- PlayerA just logs in and never opens their phone
- PlayerB sends a text msg to PlayerA
- Actual: PlayerA does not receive a notification
- Expected: PlayerA should receive a notification
The reason this is happening is because of the following error. We are trying to read `id` from `activeMessageConversation` which is undefined. 
**Fix:**
Instead of trying to read from `activeMessageConversation` we can use the `convId` that is already passed to the `addNotification` function. This is sufficient as it will always pass the id of …

Fix message notification not appearing

---

apps/game/client/cl_twitter.ts
apps/game/server/twitter/twitter.service.ts
apps/phone/src/apps/twitter/components/tweet/ShowMore.tsx
apps/phone/src/apps/twitter/hooks/useTwitterService.ts
typings/twitter.ts

**Problem:** If a player deletes a tweet, only that player will see the update in their twitter app, no other clients will receive the delete tweet event and will still be able to see the tweet.
**Fix:** When the player deletes a tweet, we will now broadcast the delete tweet event to all clients so that everyones UI reflects correctly.
- Removed the call of deleteTweet() from ShowMore.tsx, as this was only handling it for the client that did the action and is now unnecessary as the deleteTweetBroadcast event will handle calling this for all clients. 
Example:
https://github.com/project-error/npwd/assets/18689469/ca9b28ba-e2e2-433b-9fa4-efc230fd6dac
- Other player "The Man" deletes his tweets and you can see that they are removed from my UI
- I delete some of …

Fix twitter to broadcast deleted tweets to all clients

---

apps/game/server/messages/middleware/onMessage.ts

The relative path import in onMessage.ts is off. It technically needs to go up one more level `'../../../../../typings/messages';`. We can also just use the package import `@typings/messages`. 
Before import not found:
After import found:

Fix @typings import for onMessage

---

apps/phone/src/apps/twitter/components/AddTweetModal.tsx
config.default.json
typings/config.ts

In this pull request:
- Deprecated allowNoMessage configuration
- Change the way to check if the message is empty
If configuración is enabled: (Default enabled): Need message and image to send new tweet
If configuration is disabled: Message or Image
Message or image by default
The option "allowNoMessage" is a configuration that doesn't make sense, I don't see any real use for it if it's ever going to be a "true" or if anyone is going to want it that way.
**Why?** It doesn't make much sense to force someone to have to put a text AND an image and put it in a DEFAULT enabled configuration. Also don't offer FEEDBACK to the user that they are doing something wrong, 80% of people are going to think "oh, it's a bug in the phone". 
When a server administrator says "oh it's a bug in the phone" it …

Remove allowNoMessage configuration

---

apps/game/client/sounds/client-sound.class.ts

FiveM has a limit of about 100 active soundIDs, if you don't correctly release a soundID you end up with a -1 ID which ends up muting any native sounds, even native sounds outside the scope of this resource(e.g. police sirens).
Correctly release sounds IDs after use or before creating a new one.
I've also included the same fix from #1027

fix(game/sounds): release sound ids

---

apps/game/server/bridge/ndcore/ndcore-server.ts

The getcoreobject function is no longer a thing in nd v2 and the resource name is "ND_Core" not "ND-Core".

fix:(bridge/ndcore): exports & resource name

---

apps/game/server/bridge/ndcore/ndcore-server.ts

tweak(bridge/ndcore): character data & db

---

apps/game/server/calls/calls.controller.ts

In certain cases you want to know the receiving number configured within the scope of the `onCall` middleware callback. This exposes the "receiverNumber" so it would be accessible within the callback as `ctx.receiverNumber`.

feat/middleware - Expose the receiverNumber during the onCall callback middleware

---

import.sql

Fixed an explicit SQL error that caused the UNIQUE INDEX to be too long when creating a dark chat related table.
According to the MySQL INNODB limit, when using the utf8mb4 character set, you cannot set a UNIQUE INDEX longer than 191 characters. On line 208 of import.sql, the community developer misidentifies the 255 character column defined on line 205 as the index. This caused MySql to fail to execute the statement, which in turn caused the last three data tables to fail to be created. A workaround for reference is to "change" VARCHAR(255) to "VARCHAR(191)" in line 205, but you can also set 191 to any number less than it you like.
Reference: https://dev.mysql.com/doc/refman/8.0/en/innodb-limits.html

Fixed an explicit SQL error about dark_chat tables

---

apps/phone/src/common/hooks/useExternalApps.tsx

- When having multiple external apps loaded, existing apps would vanish due to `appAlreadyLoaded` returning null and not the existing app config
**Changes**
- Used nullish coalescence to determine if we require invoking `generateAppConfig`
- Remove unnecessary conditionals
- Updated `existingApps` type

fix(phone\common\hooks): correctly handle already loaded apps

---

apps/phone/src/apps/contacts/components/List/ContactList.tsx
apps/phone/src/locale/en.json
apps/phone/src/locale/sv.json

Updated sv.json with missing translations.
Updated sv.json with some minor changes in translation.
Replaced Twitter -> Life Invader, aswell as all "Tweet" & "Retweet" translations in sv.json.
Renamed "APPS_MARKETPLACE" from Blocket -> Marknadsplatsen. (Just to not use real life company names.)
Added "My Number" translation in ContactList.tsx
Added "Nearby Share" translation in ContactList.tsx
Added  "MY_NUMBER" aswell as "NEARBY_SHARE" in en.json and sv.json, for easy translations or renaming.

Update sv.json & added translation in ContactList.tsx

---

apps/phone/src/locale/fr.json

Ono missing locale :c 
* [NUH HUH] Have you built and tested NPWD in-game after the relevant change?

feat: complete french locale
