project-error/npwd

phone/src/apps/bank/components/alert/BankAlert.tsx
phone/src/apps/bank/components/notification/BankNotification.tsx
phone/src/apps/contacts/components/List/ContactList.tsx
phone/src/apps/contacts/components/alert/ContactAlert.tsx
phone/src/apps/messages/components/modal/Conversation.tsx
phone/src/apps/messages/components/modal/MessageModal.tsx
phone/src/apps/twitter/components/notification/TwitterNotification.tsx

This PR might break things, please download the branch and test INSIDE GTA!

Fix all ts warnings

---

phone/src/apps/twitter/components/AddTweetModal.tsx
phone/src/apps/twitter/components/tweet/Tweet.tsx
phone/src/apps/twitter/components/tweet/TweetMessage.tsx
phone/src/ui/components/Modal.tsx

Removes coded background and text colors and falls back to theme. Minor styling updates.

fix twitter for light theme

---

resources/client/cl_bank.ts
resources/client/cl_call.ts
resources/client/cl_contacts.ts
resources/client/cl_main.ts
resources/client/cl_messages.ts
resources/client/cl_photo.ts

Many general optimizations and improvements for client scripts

Cleanup/game scripts - Misc. cleanup of game scripts

---

phone/src/locale/fr.json

Translation: Update fr.json

---

resources/server/functions.ts
resources/server/server.ts
resources/server/sv_bank.ts
resources/server/sv_call.ts
resources/server/sv_contacts.ts
resources/server/sv_main.ts
resources/server/sv_messages.ts
resources/server/sv_notes.ts
resources/server/sv_photo.ts
resources/server/sv_sellout.ts
resources/server/sv_twitter.ts

These changes are made in case source is not guaranteed to remain the same
Due to how JS should operate, this shouldn't be an issue but this just ensures that

refactor(server/source-handling): Altered how we handle source

---

README.md

Entirely removes most of the read me as the docs contains more information in a clear and concise manner.  I will likely continue editing this throughout the week so if you have any suggestions please let me know.

Update read me to reflect docs.

---

resources/server/sv_contacts.ts

Does it for contacts app and phone app.

Sort contacts alphabetically

---

phone/src/Phone.tsx
phone/src/apps/calculator/components/CalculatorIcon.tsx
phone/src/apps/dialer/components/views/DialerHistory.tsx
phone/src/apps/home/components/Home.tsx
phone/src/apps/twitter/components/TwitterApp.tsx
phone/src/config/default.json
phone/src/locale/en.json
phone/src/os/apps/config/apps.tsx
phone/src/os/call/components/CallControls.tsx
phone/src/os/call/components/CallModal.tsx
phone/src/os/call/components/CallNotification.tsx
phone/src/os/call/hooks/useCallModal.ts
phone/src/os/call/hooks/useCallService.tsx
phone/src/os/keyboard/hooks/useKeyboardService.ts
phone/src/os/navigation-bar/components/Navigation.tsx
phone/src/os/notifications/components/NotificationAlert.tsx
phone/src/os/notifications/components/NotificationBar.tsx
phone/src/os/notifications/components/NotificationItem.tsx
phone/src/os/notifications/providers/NotificationsProvider.tsx
phone/src/os/phone/hooks/usePhone.ts
phone/src/os/phone/hooks/usePhoneVisibility.ts
phone/src/ui/components/AppIcon.tsx
phone/src/ui/components/GridMenu.tsx
phone/src/ui/components/StatusIconButton.tsx
phone/src/ui/interface/InterfaceUI.ts

Also can close alerts with X and the incoming call alert disappears if you open the phone and see the modal.
[Notification: Alert stays on if it is an incoming call and phone is closed](https://app.gitkraken.com/glo/card/5bed50e7148e45e18dfdac1ae92432e0)

Notification alert stays on if it is an incoming call and phone is closed

---

phone/src/locale/fr.json

Because it was asked to us ! 
All the english keys are now translated into baguette language + fix typo

Added missing french translations

---

phone/src/Phone.tsx
phone/src/apps/settings/components/SettingItem.tsx
phone/src/apps/settings/components/SettingsApp.tsx
phone/src/apps/settings/hooks/useSettings.ts
phone/src/config/default.json
phone/src/config/themes.json
phone/src/os/notifications/providers/NotificationsProvider.tsx
phone/src/os/phone/hooks/usePhoneTheme.ts
phone/src/os/sound/utils/getSoundSettings.ts
phone/src/ui/components/AppContent.tsx
phone/src/ui/components/Notification.tsx
phone/src/ui/hooks/useContextMenu.tsx

General enhancements to settings app

enhance(phone/settings): General enhancements

---

phone/src/Phone.tsx
phone/src/apps/settings/components/SettingsApp.tsx
phone/src/apps/settings/hooks/__tests__/useSettings.test.ts
phone/src/apps/settings/hooks/useSettings.ts
phone/src/os/notifications/providers/NotificationsProvider.tsx
phone/src/os/phone/hooks/usePhoneTheme.ts
phone/src/os/phone/hooks/usePhoneVisibility.ts
phone/src/os/sound/hooks/useRingtoneSound.ts
phone/src/os/sound/utils/getSoundSettings.ts
phone/src/ui/hooks/useContextMenu.tsx

Feature / Add schema validation for settings

---

phone/src/apps/messages/components/modal/MessageModal.tsx
phone/src/apps/messages/hooks/useMessageService.ts

Also fixed bug where u needed to open messages app to get notifications.
[Tweak: Improve transition to messageModal (Conversations)](https://app.gitkraken.com/glo/card/a16d6bac385142b8bdbe021ff14df9d2)

Tweak / Improve transition to MessageModal (conversation)

---

phone/src/apps/messages/components/form/MessageInput.tsx

fix(messages): Sliding phone up and down when mesages apps is open

---

phone/src/Phone.tsx
phone/src/ui/components/WindowSnackbar.tsx
resources/client/cl_main.ts

Can be activated by using `phone:restart` in the F8 console. This will reload the entire frame.
[feat(client/debug): Phone restart command](https://app.gitkraken.com/glo/card/4106204ed1ca494facc34e510a49cb66)

feat(client/debug): Phone restart command

---

phone/src/Phone.tsx
phone/src/apps/messages/hooks/useMessageService.ts
phone/src/locale/en.json
phone/src/os/phone/hooks/state.ts
phone/src/os/phone/hooks/usePhone.ts
phone/src/os/phone/hooks/usePhoneService.ts
resources/client/cl_main.ts

Show initializing phone message if not ready yet
Set phone ready before sending any init events

Fix the fucking esx errors :)

---

resources/client/cl_main.ts
resources/server/functions.ts
resources/server/players/sv_player_events.ts
resources/server/players/sv_players.ts
resources/server/server.ts
resources/server/sv_bank.ts
resources/server/sv_call.ts
resources/server/sv_contacts.ts
resources/server/sv_main.ts
resources/server/sv_messages.ts
resources/server/sv_notes.ts
resources/server/sv_players.ts
resources/server/sv_sellout.ts
resources/server/sv_twitter.ts
resources/typings/players.ts
resources/utils/events.ts

Removes almost all ESX code,.
[Feat: Remove ESX Code](https://app.gitkraken.com/glo/card/dae2624dcdcc45d9ab0077ad5fb58425)

feat(resources): remove all esx code, almost

---

phone/src/apps/messages/components/MessagesApp.tsx
phone/src/apps/messages/components/modal/MessageModal.tsx

Some stuff still missing.
[Fix remaining issues for messages](https://app.gitkraken.com/glo/card/ce6e8fbc44b84b87a2dcb2b39e5d14c5)

Fix remaining issues for messages

---

phone/src/Phone.tsx
phone/src/apps/messages/components/MessagesApp.tsx
phone/src/apps/messages/components/modal/MessageBubble.tsx
phone/src/apps/sellout/components/SelloutList/SelloutItem.tsx
phone/src/apps/settings/components/SettingItem.tsx
phone/src/apps/settings/components/SettingsApp.tsx
phone/src/apps/settings/hooks/useSettings.ts
phone/src/apps/twitter/components/EmojiSelect.tsx
phone/src/apps/twitter/components/TwitterApp.tsx
phone/src/apps/twitter/components/buttons/ControlButtons.tsx
phone/src/apps/twitter/components/buttons/LikeButton.tsx
phone/src/apps/twitter/components/buttons/RetweetButton.tsx
phone/src/apps/twitter/components/buttons/SearchButton.tsx
phone/src/apps/twitter/components/images/Image.tsx
phone/src/apps/twitter/components/images/ImageDisplay.tsx
phone/src/apps/twitter/components/profile/Profile.tsx
phone/src/apps/twitter/components/tweet/Retweet.tsx
phone/src/apps/twitter/components/tweet/Tweet.tsx
phone/src/apps/twitter/hooks/useTwitterNotifications.ts
phone/src/apps/twitter/hooks/useTwitterService.ts
phone/src/apps/twitter/twitter.theme.ts
phone/src/config/default.json
phone/src/locale/en.json
phone/src/os/apps/config/apps.tsx
phone/src/os/call/components/CallModal.tsx
phone/src/os/sound/utils/getSoundSettings.ts
phone/src/ui/components/PictureReveal.tsx

Add streamer mode setting and PictureReveal component for Twitter Messages Sellout images.
Improved twitter theme a bit as well.
[Feature / Streamer Mode](https://app.gitkraken.com/glo/card/33aeefccdaea491c9577c3e685d1f742)

Feature / Streamer Mode

---

README.md
import.sql
phone/src/apps/camera/components/CameraApp.tsx
phone/src/apps/sellout/components/SelloutApp.tsx
phone/src/os/debug/InjectDebugData.ts

dont mind the 347 changed files its cause i drag and dropped :alien:

replaced all imgur images to iodine images :)

---

import.sql
resources/client/cl_call.ts
resources/server/sv_call.ts
resources/server/sv_messages.ts
resources/server/sv_notes.ts
resources/server/sv_photo.ts
resources/server/sv_sellout.ts
resources/server/sv_twitter.ts

Have not yet tested in game
[Misc Cleanup of Server Side](https://app.gitkraken.com/glo/card/d7897a50cff44eafb7749e378eb32b2e)

Misc Cleanup of Server Side

---

phone/src/Phone.tsx
phone/src/apps/example/components/ExampleApp.tsx
phone/src/apps/messages/components/form/NewMessageGroupForm.tsx
phone/src/apps/messages/components/list/MessageGroupItem.tsx
phone/src/apps/messages/components/list/MessagesList.tsx
phone/src/apps/messages/components/modal/MessageModal.tsx
phone/src/apps/messages/hooks/useMessageNotifications.ts
phone/src/apps/messages/hooks/useMessageService.ts
phone/src/apps/messages/utils/goToConversation.ts
phone/src/apps/settings/utils/getRingtonePath.ts
phone/src/apps/twitter/utils/constants.ts
resources/server/sv_messages.ts

Handle offline messages 
Fetch messages and groups when broadcasted

Messages bugfix again :D

---

phone/src/apps/messages/hooks/useMessageNotifications.ts
phone/src/apps/messages/hooks/useMessageService.ts
phone/src/apps/messages/utils/goToConversation.ts

Remove message notifications when opening one
Dont alert notifications when inside that conversation

Tweaks / Message notifications

---

phone/src/os/notifications/components/NotificationBar.tsx
phone/src/os/phone/hooks/state.ts
phone/src/os/phone/hooks/usePhoneService.ts
phone/src/os/phone/hooks/usePhoneTime.ts
resources/client/cl_main.ts

Adds the current game time to the top bar, the game time is sent every time the phone is opened. This can also be done in a set interval, but I have commented that for now.

feat(phone): Added a game time indicator to top bar

---

import.sql

Fixes error with coalition not existing

fix(sql): don't include extra SQL data

---

phone/src/apps/messages/components/form/MessageInput.tsx
phone/src/os/phone/hooks/usePhoneService.ts
resources/client/cl_main.ts
typings/phone.ts

Player Ready also needs to know if NUI is loaded seems like, as events are not being received at that point, so now the two moments race and whatever is first will fetchOnInit

Fix fetch on initialize (fixing notifications too)

---

phone/src/locale/fr.json

Here I am, rock you like a french baguette ♫
Here are the new translations, waiting for moar

Adding french missing translations

---

fxmanifest.lua
resources/client/cl_main.ts
resources/client/client.ts
resources/server/functions.ts
resources/server/server.ts
resources/server/sv_logger.ts
resources/server/sv_match.ts
resources/server/sv_twitter.ts
resources/utils/config.ts

This tackles #206 allowing for the config to be edited without requiring the user to rebuild.

feat(config): Allow config to be edited without rebuild

---

phone/package.json
phone/src/os/apps/components/AppWithStartup.tsx
phone/src/os/apps/config/apps.tsx
phone/src/os/call/components/CallNotification.tsx
phone/src/os/keyboard/hooks/useKeyboardService.ts
phone/src/wdyr.ts
phone/yarn.lock

Prevents infinite renders in some apps.
Adds why-did-you-render tool in development
Fixes re-renders in useKeyboard

Add wdyr and make AppRoute a pure component

---

phone/package.json
phone/src/apps/match/components/MatchApp.tsx
phone/src/apps/twitter/components/tweet/TweetListContainer.tsx
phone/yarn.lock

Fix Nui.send effect dependencies
Upgrade lib to fixed version

Tweak / Effect dependencies and Fivem-Nui-lib

---

package.json
yarn.lock

Added webpack (required for build)
Added @octokit/core (required by lerna)
Pre-Commit to NPX

fix(build): Fix package.json

---

README.md
import.sql
phone/src/apps/camera/components/CameraApp.tsx
phone/src/apps/marketplace/hooks/state.ts
phone/src/locale/fr.json
phone/src/os/debug/InjectDebugData.ts

Because I got some noodles in my baguette, and I prefer to redo it properly

(Re)Adding french missing translations

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
package.json

Just a simple collection of GH community related tasks.

GH Community Items

---

.github/ISSUE_TEMPLATE/bug-report.yml

fix: Add version to issue label

---

.github/ISSUE_TEMPLATE/bug-report.yml

chore(bug-report): Update bug-report template

---

phone/src/apps/contacts/components/List/ContactList.tsx

Fix Contact Text Overflow on Long names or numbers

---

resources/client/animations/animation.service.ts
resources/client/calls/cl_calls.service.ts

Resolves https://github.com/project-error/npwd/issues/361
Call animation gets triggered only on accept now.

fix: resolve animation being triggered on call notification

---

resources/client/calls/cl_calls.service.ts
resources/client/cl_exports.ts
resources/client/cl_main.ts
resources/client/cl_photo.ts
resources/client/cl_utils.ts
resources/client/types/global.d.ts
resources/server/players/player.controller.ts
resources/server/players/player.service.ts
resources/server/utils/miscUtils.ts
typings/phone.ts

Minor cleanup for loading playerdata (mostly related to multicharacter).

Tweak PLAYER_READY control flow & cleanup

---

resources/server/calls/calls.service.ts

fix: emit CALL_ENDED and CALL_REJECTED events to both source and target

---

phone/craco.config.js
phone/package.json
phone/tsconfig.json
phone/tsconfig.paths.json
phone/yarn.lock

Using `craco-alias` package and `tsconfig.paths.json` file introduce path aliases in cra app.

Use cra path aliases

---

resources/server/marketplace/marketplace.service.ts

Previously these would trigger regardless if a listing was reported or not. This resolves that issue

fix(server/marketplace): add else statement for reporting listing

---

phone/src/locale/cs.json

Changed some incorrect translations and grammar errors.
Translated few missing keys.

tweak(locales/cs): Text correction

---

README.md

Update read me to reflect current release.

---

README.md

chore: resolve missing link

---

phone/src/config/default.json
phone/src/i18n.ts
phone/src/locale/fi.json

Finnish translation

---

phone/src/config/default.json
phone/src/i18n.ts
phone/src/locale/it.json

feat(locale/it): Added Italian lang file

---

phone/src/config/default.json
phone/src/i18n.ts
phone/src/locale/pl.json

feat(locale/pl): Add Polish language translations

---

README.md

chore: update read me to include discord URL.

---

phone/src/apps/marketplace/components/form/ListingForm.tsx
phone/src/apps/marketplace/hooks/state.ts

This is a fix for issue #450.
I can redo it with just React state instead of the recoil state but it would only complicate things imo.
It also clears the field after a succesful post was created

fix(marketplace): fixed input field resetting after image selection

---

phone/src/locale/fr.json

Mission translation in french + typo

---

phone/src/locale/fr.json

Faster than Chip, I saw it before he thought about it

French translation asap

---

phone/src/config/default.json
phone/src/i18n.ts
phone/src/locale/id.json

feat(locale/id): added indonesia language

---

phone/src/config/default.json
phone/src/locale/ba.json

locale(ba): updated bosnian locale

---

phone/src/apps/messages/components/modal/MessageModal.tsx

refactor(messages): remove modal & replace with icons

---

README.md

chore: properly organize the intro

---

phone/src/os/call/hooks/state.ts
phone/src/os/call/hooks/useCall.ts
phone/src/os/call/hooks/useCallService.tsx
phone/src/os/debug/AttachWindowDebug.ts
phone/src/os/navigation-bar/components/Navigation.tsx
phone/src/os/navigation-bar/state/navigation.state.ts
phone/src/os/sound/hooks/useRingtoneSound.ts
phone/tsconfig.json
resources/client/calls/cl_calls.service.ts
typings/call.ts

Adds a tone during the dialing phase of an outgoing request. This ends once the phone call is ended or once it is accepted.

[Calling] Feat: Dialing Tone during Outgoing Request Phase

---

phone/src/locale/fi.json

Updated Finnish translation

---

phone/src/os/notifications/components/NotificationBar.tsx

Resolves #511, the biggest priority issue of them all

fix(phone/notification-bar): center time text

---

phone/src/apps/twitter/components/AddTweetModal.tsx
phone/src/apps/twitter/components/ModalBackground.tsx
phone/src/apps/twitter/components/TwitterApp.tsx
phone/src/apps/twitter/components/TwitterContainer.tsx

This fixes rerendering the entire Twitter app on every letter type in AddTweetModal.

fix(twitter): fix rerendering twitter app on every letter type

---

resources/client/cl_photo.ts

feat(client/photo): show take picture key

---

phone/package.json
phone/src/Phone.test.tsx
phone/src/Phone.tsx
phone/src/apps/settings/hooks/useInvalidSettingsHandler.ts
phone/src/apps/settings/state/settings.state.ts
phone/src/apps/settings/state/settingsState.test.tsx
phone/src/apps/settings/utils/constants.ts
phone/src/apps/settings/utils/schema.ts
phone/src/setupTests.ts
phone/yarn.lock

Adds some unit tests for settings state manipulation. This also takes the chance to move away from Enzyme, instead utilizing the `testing-library` project.

test(phone/settings): add unit tests for setting state

---

phone/src/apps/twitter/hooks/useTwitterNotifications.ts

fix(twitter): only play sounds on player mention

---

build-detector.js
fxmanifest.lua

since reading/downloading can be hard for people, lets hold some hands
@TasoOneAsia did this so if it breaks anything its taso's fault.

feat(server/build-detector): inform user of missed build step

---

README.md

chore: update read me to be less specific

---

resources/client/calls/cl_calls.service.ts
resources/client/cl_main.ts

fix(call): fix being able to accept calls if player has no phone

---

phone/src/apps/twitter/components/tweet/TweetMessage.tsx

Small typo fix for the character limit translation

fix(phone/twitter) typo for i18n

---

phone/src/locale/es.json

Spanish locale file fixed and updated. (Missing translations and better "Spanish")
* [ X ] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [ X ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [ X ] Have you built and tested NPWD in-game after the relevant change?

Update and fix for spanish locale

---

phone/src/locale/newtr.json

Create New tr.json

---

phone/src/apps/twitter/components/profile/Profile.tsx
resources/client/cl_exports.ts

Cherrypicked version of #615 and #614 created by @antond15.

Misc. Fixes for Exports & typos

---

resources/client/cl_main.ts
resources/server/boot/boot.controller.ts
resources/server/boot/boot.db.ts
resources/server/boot/boot.service.ts
resources/server/boot/boot.utils.ts
resources/server/server.ts

This PR adds a boot controller that will perform various tasks/checks when the server resource starts and also adds a simple export check if PhoneAsItem is enabled.
This is WIP for a few reasons:
- Do you guys want this to be a controller/service or just a bunch of util functions I run in the server.ts file on startup?
- If it should be a controller/service, is "boot" the correct name? I think it accurately describes whats happening but I would like input.
- If boot is fine, should I remove the onServerResourceStart event handler from server.ts and provide confirmation after checks have been completed?
- After each check should I be providing confirmation that it passed or just log when an error occurs?
- How should the logs be formatted? Do we want a huge box …

Debug stuff

---

phone/src/apps/calculator/components/Calculator.tsx

Decrease the font-size of result based on length of calculation.

feat(app/calculator): decrease font-size based on result length

---

resources/server/commands/registerCommands.ts
resources/server/db/parseUri.ts
resources/server/server.ts
resources/server/sv_logger.ts

Introduces a debug command that will write out useful debug information regarding the environment NPWD is installed in, this should help ease support.
This also takes the chance to tweak the File transport logger to always write out to sv_npwd.log, no matter the debug level. Furthermore, Console transport is now tied directly to the config debug level, instead of inheriting from base logger instance.

feat(server/debug): introduce 'npwd-debug-dump' command

---

phone/src/apps/match/hooks/useMatchActions.ts
phone/src/apps/twitter/hooks/state.ts
phone/src/lib/RecoilCacheReset.tsx
phone/src/lib/RecoilRootManager.tsx
resources/server/match/match.controller.ts
resources/server/match/match.db.ts
resources/server/match/match.service.ts

Moar bug fixes

---

import.sql

Many people have the problem of the foreign key, because of the wrong order in the query.

Fix the .sql problem

---

phone/src/config/default.json
phone/src/locale/cs.json

Added all missing translations for Czech language.

feat(locale/cs): Add missing translations

---

phone/src/locale/fr.json

Hey, I'm back (kinda)
Missing translation is added and I've fixed some punctation issues and little typos !

Missing translations + somes fixes

---

phone/src/config/default.json

Add a new zoom option to the phone which need to be scaled up with 4K monitors.

feat(config): add a new zoom option

---

phone/src/locale/ar.json

Although I am not sure if RTL will be supported, here is the Arabic translation for the application...
An additional note to make it more grammatically correct: in line 242; the relative time counting system will not be correct grammatically unless additional values for when it is 2 minutes/2 hours/2 days/2 months/ 2 years are added in

Addition of Arabic Translation

---

.github/stale.yml

Small chore to automate stale issue management
* [N/A] Have you built and tested NPWD in-game after the relevant change?

chore(.github): stale issue automation

---

phone/src/locale/ar.json

fixed a comma in arabic locale *facepalm*

---

phone/src/locale/no.json

Improved some of the norwegian translations.

Updated norwegian (no) translation

---

phone/src/locale/hu.json

_A few missing or incorrect translations have been updated._

Minor hungarian (hu) translation fixes

---

resources/server/calls/calls.controller.ts
resources/server/calls/middleware/onCall.ts
typings/call.ts

Introduces middleware for intercepting phone calls offering the following functionality:
```ts
interface IncomingCallerCtx {
source: number;
number: string;
name: string;
}
interface OnCallExportCtx {
incomingCaller: IncomingCallerCtx; // incoming caller context
exit: () => void; // Exits the phone call for the caller
next: () => void; // Allows the number to ring out to the default handler
reply: (msg: string) => void; // Sends a text message to the caller
forward: (tgt: string) => void; // Forwards the call to a new number
}
```

Feature: onCall export middleware

---

phone/src/apps/camera/components/CameraApp.tsx
phone/src/apps/camera/components/NewPhotoButton.tsx
phone/src/apps/camera/components/grid/GalleryGrid.tsx
phone/src/apps/camera/hooks/state.ts
phone/src/apps/camera/hooks/usePhotoActions.ts
phone/src/apps/camera/utils/constants.ts
resources/client/cl_photo.ts
resources/server/photo/photo.controller.ts
resources/server/photo/photo.db.ts
resources/server/photo/photo.service.ts
typings/photo.ts

feat: delete multiple photos

---

phone/src/apps/messages/components/modal/MessageBubble.tsx

fix(phone/messages): bubble menu not showing

---

phone/src/locale/fr.json

Here I am, completing some new translations !

Missing french translations

---

phone/src/locale/da.json

Added danish language to the phone

Added danish lang

---

config.default.json
config.json
phone/src/apps/contacts/components/List/ContactItem.tsx
phone/src/apps/contacts/components/List/ContactList.tsx
typings/config.ts

Proposal for supporting default contacts through config.

feat(phone/contacts): option for default contacts

---

.github/actions/bump-manifest-version.js
.github/workflows/tagged-releases.yml

Should resolve issues with the fxmanifest verison in the resource not matching the version on the tag by updating the file on the tag itself.

ci(release): improve the manifest bumper

---

apps/game/client/cl_photo.ts

Added an if statement, if the players hud is showing, It will hide it until the user takes a photo /or exits the camera. If the hud is hidden by another resource, It will do nothing.
Will hide all hud scripts which have `IsHudHidden()` within the code.

Update In Camera Mode for HUD resources

---

apps/game/client/cl_photo.ts

A couple weeks ago, My PR got approved to hide the HUD while taking pictures, but didnt think to hide the radar itself as well.
So this new change/PR hides the radar as well while taking pictures.

Update Camera App to hide the Radar.

---

config.default.json

fix: fix config not allowing i.fivemanage.com

---

packages/database/src/db/parseUri.ts

- Adds types to connection URI 
- Correctly parses connection URI options
Note, that this supports the following connection string types
```
set mysql_connection_string "mysql://root:12345@localhost:3306/npwd"
set mysql_connection_string "mysql://localhost:3306/npwd?user=12345&password=12345"
set mysql_connection_string "user=root;password=12345;host=localhost;port=3306;database=npwd"
```

fix(packages/db): type safe & parse uri options

---

packages/database/src/db/parseUri.ts

- Supports special characters in password for connection URI

fix(packages/db): special characters in passwords

---

packages/database/src/db/parseUri.ts

This fixes the cases mentioned in https://github.com/project-error/npwd/issues/1094
**Notes**
- No password cases were being treated as a regex case, this is not the case
- Driver hates empty strings in the options

fix(packages/db): no password cases

---

apps/game/server/bridge/ndcore/ndcore-server.ts

fix(bridge/ndcore): toString on null

---

apps/game/server/contacts/contacts.database.ts
typings/config.ts
typings/contact.ts

_This PR will prepend the default contacts configured in the script to the dataset returned from the database query. Users also do not have to "guess" an incremented integer to supply a proper key, it is now formed from the display name and number._

Implement default contacts back into NPWD

---

apps/phone/src/i18n.ts

added import da from './locale/da.json';
and here ya go, thats the next one :) AND you still rock <3
* [x ] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [ no] Have you built and tested NPWD in-game after the relevant change? But I had a great mentorship for this !

Update i18n.ts add da for danish locales

---

apps/phone/src/locale/pl.json

I added missing translations and improved already existing ones.

Polish translation update

---

apps/phone/src/locale/fr.json

Updates the locales according to 3.14.3
I'd personally prefer nearby share to just be nearby share (since that's how it's called in android duh?), but it's not french enough!!!
:fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr: :fr:

feat: update french locales
